services:
  postgres:
    image: postgres:16
    container_name: sa-civic-pulse-db
    restart: unless-stopped

    # postgres environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432" # postgres port number and accessible port number
    volumes:
      - postgres_data:/var/lib/postgresql/data # keeps data even if container restarts (db layer)

volumes:
  postgres_data: