"""
main.py

The API layer. currently 1 endpoint, just a Python function that runs a
SQL query and returns the result -- FastAPI handles turning that into JSON.

endpoints:
    1) /docs -> autogenerated 
    2) [GET] :
        3.1) -> /
        3.2) -> /docs *** Fast Api automatically creates this
        3.3) -> /events         	A list of individual events

        3.4) -> /event-types/top	Which CAMEO categories occur most
        3.5) -> /sentiment/trend	Average tone per month, optionally per-province

How to run:
    uvicorn api.main:app --reload
Then visit http://localhost:8000/docs for interactive docs (auto-generated, free).
"""

import os
from datetime import date
from typing import Optional

import psycopg2
import psycopg2.extras
from fastapi import FastAPI, Query, HTTPException, Path
import logging

app = FastAPI(title="SA Civic Pulse API")

logger = logging.getLogger(os.getenv("POSTGRES_DB"))


DB_CONFIG = {
    "host": os.getenv("POSTGRES_HOST"),
    "port": os.getenv("POSTGRES_PORT"),
    "dbname": os.getenv("POSTGRES_DB"),
    "user": os.getenv("POSTGRES_USER"),
    "password": os.getenv("POSTGRES_PASSWORD"),
}


## ----------------------- helper methods ------------------------ ##
def run_query(sql: str, params: Optional[list | tuple] = None, fetch_one: bool = False):

     # POSGRES CONNECT start up
    conn = psycopg2.connect(**DB_CONFIG)

    try:
        conn = psycopg2.connect(**DB_CONFIG)
    except psycopg2.OperationalError as e:
        logger.error(f"Could not connect to Postgres: {e}")
        raise HTTPException(status_code = 503,
                            detail = "Database is currently unavailable")

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, params or ())
            if fetch_one:
                return cur.fetchone()
            return cur.fetchall()
    finally:
        conn.close()
## --------------------------------------------------------------- ##

# -> http://localhost:8000/
@app.get("/")
def root():
    return {"message": "SA Civic Pulse API -- see /docs for available endpoints"}


# -> http://localhost:8000/events
@app.get("/events")
def get_events(
    province: Optional[str] = Query(None, description="Province name, e.g. 'Western Cape'"),
    start_date: Optional[date] = Query(None, description="YYYY-MM-DD"),
    end_date: Optional[date] = Query(None, description="YYYY-MM-DD"),
    limit: int = Query(50, le=500, description="Max rows to return"),
):
    """Events filtered by province and/or date range."""
    conditions = []
    params = []

    if province:
        conditions.append("loc.province_name = %s")
        params.append(province)
    if start_date:
        conditions.append("t.sql_date >= %s")
        params.append(start_date)
    if end_date:
        conditions.append("t.sql_date <= %s")
        params.append(end_date)

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""

    sql = f"""
        SELECT f.global_event_id, t.sql_date, loc.province_name,
               et.category_label, f.actor1_name, f.actor2_name,
               f.avg_tone, f.goldstein_scale, f.source_url
        FROM event_fact f
        JOIN event_time t ON f.date_key = t.date_key
        JOIN event_location loc ON f.location_id = loc.location_id
        JOIN event_action_type et ON f.event_type_id = et.event_type_id
        {where_clause}
        ORDER BY t.sql_date DESC
        LIMIT %s
    """
    params.append(limit)

    return run_query(sql, params)


# 1. Discovery — "what's even in here?"
# GET /provinces — list of provinces with event counts each
# curl http://127.0.0.1:8000/provinces
@app.get("/provinces")
def get_provinces(
    min_count: int = Query(0, ge=0, description="Exclude provinces below this event volume"),
):
    """List of all recorded provinces with total event counts and average tone"""
    sql = """
        SELECT 
            loc.province_name,
            loc.adm1_code,
            COUNT(f.global_event_id) AS event_count,
            ROUND(AVG(f.avg_tone)::numeric, 2) AS avg_tone
        FROM event_location loc
        LEFT JOIN event_fact f ON loc.location_id = f.location_id
        WHERE loc.province_name IS NOT NULL
        GROUP BY loc.province_name, loc.adm1_code
        HAVING COUNT(f.global_event_id) >= %s
        ORDER BY event_count DESC
    """
    return run_query(sql, (min_count,))

# GET /event-types — list of all CAMEO categories with counts (same idea, for the category_label filter)
# curl http://127.0.0.1:8000/event-types/top
@app.get("/event-types/top")
def get_top_event_types(
    limit: int = Query(5, ge=1, le=50, description="Top N CAMEO event types to return"),
    province: Optional[str] = Query(None, description="Optional province filter"),
):
    """Which CAMEO categories occur most frequently overall or in a target province"""
    conditions = []
    params = []

    if province:
        conditions.append("loc.province_name = %s")
        params.append(province)

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""

    sql = f"""
        SELECT 
            et.cameo_root_code,
            et.category_label,
            et.quad_class,
            COUNT(f.global_event_id) AS event_count
        FROM event_fact f
        JOIN event_action_type et ON f.event_type_id = et.event_type_id
        JOIN event_location loc ON f.location_id = loc.location_id
        {where_clause}
        GROUP BY et.cameo_root_code, et.category_label, et.quad_class
        ORDER BY event_count DESC
        LIMIT %s
    """

    params.append(limit)
    return run_query(sql, params)


# GET /events/count — total matching a filter, without pulling every row (useful before deciding whether to actually fetch /events with that filter)
# curl http://127.0.0.1:8000/events/count
@app.get("/events/count")
def get_events_count(
    province: Optional[str] = Query(None, description="Province name, e.g. 'Western Cape'"),
    start_date: Optional[date] = Query(None, description="YYYY-MM-DD"),
    end_date: Optional[date] = Query(None, description="YYYY-MM-DD"),
    cameo_root_code: Optional[str] = Query(None, description="Cameo root code, e.g. '14'"),
):
    """Get the total count of events matching specific criteria without fetching full payloads."""
    conditions = []
    params = []

    if province:
        conditions.append("loc.province_name = %s")
        params.append(province)
    if start_date:
        conditions.append("t.sql_date >= %s")
        params.append(start_date)
    if end_date:
        conditions.append("t.sql_date <= %s")
        params.append(end_date)
    if cameo_root_code:
        conditions.append("et.cameo_root_code = %s")
        params.append(cameo_root_code)

    where_clause = f"WHERE {' AND '.join(conditions)}" if conditions else ""

    sql = f"""
        SELECT COUNT(*) AS total_events
        FROM event_fact f
        JOIN event_time t ON f.date_key = t.date_key
        JOIN event_location loc ON f.location_id = loc.location_id
        JOIN event_action_type et ON f.event_type_id = et.event_type_id
        {where_clause}
    """

    result = run_query(sql, params, fetch_one=True)
    return result

# GET /events/{id} — one event's full detail, for when an aggregate number looks interesting and someone wants to see what's actually behind it
# curl http://127.0.0.1:8000/events/<insert event id>
@app.get("/events/{event_id}")
def get_event_by_id(
    event_id: int = Path(..., description="The GLOBALEVENTID of the event"),
):
    """Fetch complete detail for a single event."""
    sql = """
        SELECT 
            f.global_event_id,
            t.sql_date,
            t.year,
            t.month,
            loc.adm1_code,
            loc.province_name,
            loc.country_code,
            et.cameo_root_code,
            et.cameo_base_code,
            et.quad_class,
            et.category_label,
            f.actor1_name,
            f.actor1_country,
            f.actor2_name,
            f.actor2_country,
            f.goldstein_scale,
            f.avg_tone,
            f.num_mentions,
            f.num_sources,
            f.num_articles,
            f.source_url,
            f.date_added
        FROM event_fact f
        JOIN event_time t ON f.date_key = t.date_key
        JOIN event_location loc ON f.location_id = loc.location_id
        JOIN event_action_type et ON f.event_type_id = et.event_type_id
        WHERE f.global_event_id = %s
    """

    event = run_query(sql, (event_id,), fetch_one=True)
    if not event:
        raise HTTPException(status_code=404, detail=f"Event {event_id} not found")
    return event